export const NormaGroup = {
    id: 'norma',
    lightBg:true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Position: Research & Development Intern',
    headline: 'NORMA Group',
    description: 'At NORMA Group I worked with the director of research and development building a web application from the ground up. The tech stack was React(Javascript) frontend, Flask(Python) backend, and a Microsoft SQL database hosted on an Azure app service. This was my first experience creating an application that would be put into production, So I had many new things to learn which was exciting for me. Throughout the process I learned about how to set up a SQL database, App Service with continuous integration, and how to communicate between the app service and the database using a backend. Throughout my classes at Michigan State I did a lot of parsing excel files and this was the first time I was doing that for the purpose of a real problem. The application Itself parsed excel files of test results, and presented them in a meaningful way on the frontend that was manipulatable so that engineers could view the data in whatever scope was most valuable for them. This saved the engineers of NORMA group the time and tedious effort of doing this all themselves.',
    buttonLabel: 'Norma',
    imgStart: true,
    img: require('../../Images/norma.png'),
    alt: 'NORMA Group',
    dark: true,
    primary: true,
    darkText: true,
    link: "https://www.normagroup.com/corp/en/home/",
}
export const LockheedMartinSpace  = {
    id: 'Lockheed',
    lightBg:true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'MSU Capstone Project',
    headline: 'Lockheed Martin Space',
    description: 'The most interesting class I had at Michigan State was my capstone. My capstone had me working directly with members of Lockheed Martin Space out of Colorado. The project my team and I were assigned was working on an web application appstore for their satellites. The tech stack for the application was Flask, React, Docker, Jenkins, PostgreSQL, Nexus Repository Manager, Conan C++ Package Manager. We also had 3 different motherboards that we had to connect to and run tests on. This was my first experience working with hardware and that was really exciting, as I was able to apply my knowledge from past experiences and classes fairly easily to a new type of problem. I often spent 40+ hours in the lab, working on this appstore with my team, and learning the new technologies. By the end of the class and project I had learned enough to be extremely proud of myself and my peers. With the knowledge I learned from this project as well as my other Internship I am confident I can create any web application idea that comes to my mind. Thus I am setting up this website so that I can experiment and explore those ideas.',
    buttonLabel: 'Lockheed Martin Space',
    imgStart: false,
    img: require('../../Images/lockheed.png'),
    alt: 'Lockheed Martin Space',
    dark: false,
    primary: false,
    darkText: true,
    link: "https://www.lockheedmartin.com/en-us/capabilities/space.html",
}

export const Bowling = {
    id: 'Bowling',
    lightBg:true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'This Website',
    headline: 'What is this website?',
    description: 'This website first and foremost is a portfolio right now. I plan on making this website a library of proof of concepts and side projects that I work on in my freetime. As of now I have a blog page, which I use to keep track of my progress on this website, as well as sometimes I add random thoughts I have in there. The sandbox page is where I test new components and side projects before they get their own page.',
    buttonLabel: 'SandBox',
    imgStart: false,
    img: require('../../Images/Bowling.png'),
    alt: 'Bowling',
    dark: false,
    primary: false,
    darkText: true,
    link: "/Sandbox",
}